/* スポットデータ（2026年8月調査）
   掲載基準: 犬の入水OK / 駐車場あり / 犬連れ飲食店 / 日陰・路面環境
   ⚠️ ルールは変更されることがあるため、おでかけ前に公式情報を確認 */
const SPOTS = [
  /* ---------- 川・渓流 ---------- */
  {
    id: "akigawa",
    name: "秋川渓谷（十里木河原・石舟橋周辺）",
    category: "river",
    area: "東京都あきる野市",
    lat: 35.7286, lng: 139.2213, elevation_m: 230,
    driveMin: 80,
    water: { allowed: true, depth: "泳げる深さあり", note: "浅瀬中心だが淵もあり犬が泳げる。犬連れ川遊び・BBQの実績多数。流れは緩やか" },
    parking: [
      { name: "十里木駐車場（市営）", fee: "無料", note: "河原まで徒歩5分。夏は午前中に満車" },
      { name: "荷田子駐車場", fee: "1,000円/日", note: "駐車場すぐ脇の河原で泳げる。8時台到着推奨" },
    ],
    restaurants: [
      { name: "黒茶屋", policy: "テラスのみ", leadOK: true, note: "築300年古民家の食事処。犬同伴は指定テラス席のみ。要事前確認" },
    ],
    surface: { shade: "普通", ground: "砂利・岩" },
    notes: "夏の週末はBBQ客で混雑。水質良好。豪雨後は河原の状況が変わるため出発前に要確認",
  },
  {
    id: "kamanofuchi",
    name: "釜の淵公園（多摩川）",
    category: "river",
    area: "東京都青梅市",
    lat: 35.7847, lng: 139.2568, elevation_m: 180,
    driveMin: 70,
    water: { allowed: true, depth: "泳げる深さあり", note: "浅瀬と深いゾーンが混在し、透明度の高い水。犬連れ川遊びの実績記事あり" },
    parking: [
      { name: "釜の淵公園無料駐車場", fee: "無料", note: "数台分のみ。休日は満車が続く" },
      { name: "市営釜の淵公園大柳駐車場", fee: "数百円/日程度", note: "河原まで徒歩5分程度" },
    ],
    restaurants: [
      { name: "ome smash burger 杉屋", policy: "テラスのみ", leadOK: true, note: "釜の淵公園内。テラス席ペットOK。火・水定休" },
    ],
    surface: { shade: "普通", ground: "砂利・岩（公園側は芝生と木陰）" },
    notes: "夏は釣り・川遊び客で賑わう。深い淵は流れに注意。「わんにゃんおうめお出かけマップ」で周辺の犬連れ店を確認可能",
  },
  {
    id: "tashiro-nakatsugawa",
    name: "田代運動公園前 中津川河川敷",
    category: "river",
    area: "神奈川県愛甲郡愛川町",
    lat: 35.5321, lng: 139.2905, elevation_m: 90,
    driveMin: 60,
    water: { allowed: true, depth: "泳げる深さあり", note: "透明度が高く川幅も広い。浅瀬と泳げる淵の両方あり。犬連れ川遊びの実績あり" },
    parking: [
      { name: "田代運動公園駐車場", fee: "無料", note: "河川敷隣接" },
      { name: "河川敷（車両乗り入れ可）", fee: "無料", note: "川沿いまで直接乗り入れ可。土日祝は朝早くに埋まる" },
    ],
    restaurants: [
      { name: "服部牧場（カサリンガのジェラート）", policy: "テラスのみ", leadOK: true, note: "車で約10分。入場・駐車無料、場内リード同伴OK" },
    ],
    surface: { shade: "少ない", ground: "砂利" },
    notes: "無料のため夏の週末は非常に混雑、BBQ客多め。川崎から最も近い本格川遊びスポットの一つ",
  },
  {
    id: "hadano-tokawa",
    name: "県立秦野戸川公園・水無川（ペット入水指定区域）",
    category: "river",
    area: "神奈川県秦野市",
    lat: 35.4152, lng: 139.1841, elevation_m: 170,
    driveMin: 60,
    water: { allowed: true, depth: "浅瀬中心", note: "公式にペット入水可の指定区域あり（川遊び場Aゾーンより下流側）。リード装着必須。浅く流れも穏やか" },
    parking: [
      { name: "大倉駐車場", fee: "530円/日程度", note: "川遊び場まで徒歩数分" },
      { name: "水無川駐車場", fee: "530円/日程度", note: "公園南側エリアに近い" },
    ],
    restaurants: [
      { name: "森のカフェ", policy: "テラスのみ", leadOK: true, note: "秦野市内。ペット同伴OKのテラス席は3席程度と少なめ" },
    ],
    surface: { shade: "少ない", ground: "砂利（一部護岸コンクリート）" },
    notes: "県立公園が公式に犬の水遊びエリアを指定している貴重なスポット。風の吊り橋と丹沢の景観",
  },
  {
    id: "doshigawa",
    name: "道志川・両国橋キャンプ場（デイキャンプ）",
    category: "river",
    area: "山梨県道志村",
    lat: 35.5516, lng: 139.1697, elevation_m: 330,
    driveMin: 95,
    water: { allowed: true, depth: "泳げる深さあり", note: "道志川は透明度抜群で流れも緩やか。犬連れ川遊びの実績あり。屋外・河原は犬同伴可" },
    parking: [
      { name: "両国橋キャンプ場場内駐車場", fee: "1,000〜1,500円＋施設利用料700円/人", note: "デイキャンプは予約不要、7〜18時。河原まですぐ" },
    ],
    restaurants: [
      { name: "道の駅どうし（屋外ベンチ）", policy: "なし", leadOK: null, note: "周辺に犬連れ入店可の飲食店は少ない。道の駅の屋外ベンチ利用が現実的" },
    ],
    surface: { shade: "多い", ground: "砂利・岩" },
    notes: "標高330m前後で夏も比較的涼しい。水質は屈指。道志みちは週末渋滞しやすい",
  },
  {
    id: "seiryuen",
    name: "清流園（名栗川／入間川上流）",
    category: "river",
    area: "埼玉県飯能市",
    lat: 35.8672, lng: 139.2648, elevation_m: 130,
    driveMin: 90,
    water: { allowed: true, depth: "泳げる深さあり", note: "浅瀬から深い場所まで多様。遠浅で水がきれい。大型犬連れの川遊び実績あり。犬は無料・予約不要" },
    parking: [
      { name: "清流園駐車場", fee: "1,000円/日〜＋入園料200円/人", note: "約130台。川の近くまで乗り入れ可。営業4〜10月、8〜17時" },
    ],
    restaurants: [
      { name: "CARVAAN BREWERY & RESTAURANT 飯能本店", policy: "テラスのみ", leadOK: true, note: "飯能河原沿い。テラス40席が犬同伴可、予約時に事前連絡" },
    ],
    surface: { shade: "普通", ground: "砂利" },
    notes: "管理された有料河原のためマナーは比較的良好。林に囲まれ午後は日陰ができる",
  },
  {
    id: "kinchakuda",
    name: "巾着田・高麗川（ドレミファ橋周辺）",
    category: "river",
    area: "埼玉県日高市",
    lat: 35.8859, lng: 139.3138, elevation_m: 85,
    driveMin: 80,
    water: { allowed: true, depth: "浅瀬中心", note: "高麗川の浅く穏やかな流れ。犬連れBBQ・川遊びの実績あり。渇水期は特に浅い" },
    parking: [
      { name: "巾着田有料駐車場", fee: "500円/日", note: "トイレ完備。川まで徒歩数分" },
    ],
    restaurants: [
      { name: "阿里山Cafe", policy: "テラスのみ", leadOK: true, note: "高麗駅近く。屋根付きウッドデッキのテラスが犬同伴可" },
    ],
    surface: { shade: "普通", ground: "砂利（川沿いに木陰あり）" },
    notes: "浅いので泳ぐより水遊び向き。芝生・遊歩道があり散歩と組み合わせやすい。曼珠沙華まつり期間（9月中旬〜10月上旬）は大混雑",
  },
  {
    id: "nagatoro",
    name: "長瀞 岩畳（荒川）",
    category: "river",
    area: "埼玉県秩父郡長瀞町",
    lat: 36.0940, lng: 139.1113, elevation_m: 130,
    driveMin: 130,
    water: { allowed: true, depth: "浅瀬中心", note: "岩畳の岸辺の浅場で犬の水遊び実績あり。荒川本流は深く流れが強い遊泳禁止箇所が多いため、入水は浅場のみ厳守" },
    parking: [
      { name: "宝登山神社大鳥居横 観光駐車場", fee: "500円/日", note: "岩畳まで徒歩約5分" },
      { name: "タイムズ長瀞駅前", fee: "60分400円〜", note: "商店街・岩畳至近" },
    ],
    restaurants: [
      { name: "エルズパーク長瀞 カフェ&バル", policy: "店内OK", leadOK: true, note: "犬同伴前提の施設。フック・マナーマット完備、宿泊者以外も利用可" },
      { name: "長瀞商店街のペットOKテラス各店", policy: "テラスのみ", leadOK: true, note: "観光協会が「ペット受け入れ可能施設一覧」を公開しており選択肢多数" },
    ],
    surface: { shade: "少ない", ground: "岩盤（岩畳）" },
    notes: "夏の岩盤は高温になるため肉球注意・朝夕推奨。ライン下りなど犬連れ観光と組み合わせられる",
  },
  {
    id: "ranzan",
    name: "嵐山渓谷バーベキュー場（槻川）",
    category: "river",
    area: "埼玉県比企郡嵐山町",
    lat: 36.0233, lng: 139.3046, elevation_m: 70,
    driveMin: 100,
    water: { allowed: true, depth: "浅瀬中心", note: "槻川は穏やかで浅く安心して川遊び可。ペット同伴可（リード必須）と施設が明示" },
    parking: [
      { name: "嵐山渓谷バーベキュー場駐車場", fee: "1,000円/日", note: "約300台。河原至近。営業3月下旬〜12月上旬、9〜16時" },
    ],
    restaurants: [
      { name: "場内併設ドッグカフェ", policy: "店内OK", leadOK: true, note: "営業状況は訪問前に要確認" },
    ],
    surface: { shade: "普通", ground: "砂利・岩" },
    notes: "手ぶらBBQができるためBBQ客は多め。管理されており炊事場・トイレが整う",
  },
  {
    id: "kinomata",
    name: "木の俣渓谷・木の俣園地",
    category: "river",
    area: "栃木県那須塩原市",
    lat: 36.9989, lng: 139.9271, elevation_m: 480,
    driveMin: 190,
    water: { allowed: true, depth: "泳げる深さあり", note: "エメラルドグリーンの透明な淵があり泳げる。リード同伴での利用可" },
    parking: [
      { name: "木の俣園地駐車場", fee: "4〜9月有料（自動精算機）", note: "駐車場からすぐで川遊び可。台数少なめで夏休みは早着推奨" },
    ],
    restaurants: [
      { name: "那須高原 清流の里", policy: "テラスのみ", leadOK: true, note: "犬連れOK食事処（釣り堀併設）。屋外席で同伴可" },
    ],
    surface: { shade: "多い", ground: "岩・砂利" },
    notes: "林間の日陰が多く夏も涼しい。水は冷たく水質抜群。遠いため早朝出発推奨、那須観光と組み合わせ向き",
  },

  /* ---------- 海 ---------- */
  {
    id: "tatarahama",
    name: "たたら浜（観音崎ビーチ）",
    category: "sea",
    area: "神奈川県横須賀市",
    lat: 35.2508, lng: 139.7420, elevation_m: 2,
    driveMin: 70,
    water: { allowed: true, depth: "泳げる深さあり", note: "海水浴場として開設されておらず夏期も犬の水遊び実績多数。遠浅で透明度高め、岩場寄りは波穏やか。リード着用推奨" },
    parking: [
      { name: "県立観音崎公園駐車場（第1〜6）", fee: "550〜880円/日", note: "たたら浜へは第4・5駐車場が近い。夏の週末は午前中に満車になりやすい" },
    ],
    restaurants: [
      { name: "アクアマーレ（横須賀美術館内）", policy: "テラスのみ", leadOK: true, note: "海を望むテラス席が犬同伴可。キッチンカーも利用可" },
      { name: "レストア（走水）", policy: "テラスのみ", leadOK: true, note: "広いテラス席で犬同伴可" },
    ],
    surface: { shade: "普通", ground: "白砂の砂浜＋両側に岩場・磯" },
    notes: "川崎から最も近い海候補。初代ゴジラ上陸の浜。ライフセーバー不在のため入水は自己責任。観音崎公園の緑地で木陰の休憩がしやすい",
  },
  {
    id: "yugawara",
    name: "湯河原海水浴場（吉浜海岸）",
    category: "sea",
    area: "神奈川県湯河原町",
    lat: 35.1466, lng: 139.1140, elevation_m: 3,
    driveMin: 90,
    water: { allowed: true, depth: "泳げる深さあり", note: "海水浴場開設期間中（例年7月中旬〜8月末）もリード着用で犬の同伴・入水OKという関東でも希少な公認ビーチ" },
    parking: [
      { name: "湯河原海浜公園駐車場", fee: "2時間無料、以降200円/30分・最大1,100円", note: "ビーチまで徒歩数分。夏期は早めの到着推奨" },
    ],
    restaurants: [
      { name: "WAKAFE（湯河原駅近く）", policy: "店内OK", leadOK: true, note: "店内に愛犬同伴席あり。名物・湯河原ナポリタン" },
      { name: "ラ・テラス岩本屋（万葉公園入口）", policy: "店内OK", leadOK: true, note: "店内ペットOKのドッグフレンドリーカフェ" },
      { name: "福浦漁港 みなと食堂", policy: "テラスのみ", leadOK: true, note: "漁港直送の海鮮。テラス席のみ犬OK" },
    ],
    surface: { shade: "少ない", ground: "砂浜（一部小石混じり）" },
    notes: "海水浴シーズンに堂々と犬と泳げる貴重な海水浴場。徒歩10分の湯河原海辺公園に海を望むドッグランあり（町外200円）。夏は遊泳者が多いので端のエリア利用がマナー",
  },
  {
    id: "tatado",
    name: "多々戸浜海水浴場",
    category: "sea",
    area: "静岡県下田市",
    lat: 34.6620, lng: 138.9220, elevation_m: 5,
    driveMin: 190,
    water: { allowed: true, depth: "泳げる深さあり", note: "下田市観光公式が「市内の海水浴場はリード着用で愛犬と海で泳ぐこともできる」と明言。夏期もOK。サーフスポットで波はやや高め" },
    parking: [
      { name: "多々戸浜駐車場（民間）", fee: "夏期2,000円〜/日", note: "約110台。温水シャワー通年あり。夏休みは早朝満車注意" },
    ],
    restaurants: [
      { name: "下田バーガー Ra-maru（道の駅開国下田みなと）", policy: "テラスのみ", leadOK: true, note: "名物・金目鯛バーガー。テラス席犬OK" },
      { name: "青木サザエ店", policy: "テラスのみ", leadOK: true, note: "大型犬まで対応実績あり。サザエ・海鮮" },
    ],
    surface: { shade: "少ない", ground: "水質AAのきめ細かい白砂" },
    notes: "透明度抜群の白砂450m。波があるため泳ぎ好きで体力のある犬向き。片道約3時間なので早朝出発推奨",
  },
  {
    id: "sotoura",
    name: "外浦海水浴場",
    category: "sea",
    area: "静岡県下田市",
    lat: 34.6910, lng: 138.9790, elevation_m: 3,
    driveMin: 180,
    water: { allowed: true, depth: "泳げる深さあり", note: "下田市内の海水浴場共通ルールでリード着用なら夏期も犬の入水OK。入り江のため遠浅で波が非常に穏やか、犬の泳ぎに安心" },
    parking: [
      { name: "外浦海岸周辺駐車場", fee: "夏期2,000円〜/日", note: "約200台。浜のすぐ裏。有料シャワー500円あり" },
    ],
    restaurants: [
      { name: "下田バーガー Ra-maru（車約10分）", policy: "テラスのみ", leadOK: true, note: "道の駅開国下田みなと内" },
      { name: "青木サザエ店（白浜・車約7分）", policy: "テラスのみ", leadOK: true, note: "大型犬対応" },
    ],
    surface: { shade: "少ない", ground: "白砂の砂浜（入り江）" },
    notes: "下田エリアで最も波が穏やかで、泳ぎ好きのコーギーがしっかり泳ぎ込める。家族連れ中心で落ち着いた雰囲気。多々戸浜より人が少なめ",
  },
  {
    id: "okinoshima",
    name: "沖ノ島公園（館山・沖ノ島の磯浜）",
    category: "sea",
    area: "千葉県館山市",
    lat: 34.9787, lng: 139.8258, elevation_m: 3,
    driveMin: 110,
    water: { allowed: true, depth: "泳げる深さあり", note: "島の周囲の磯・浜はリード着用で通年犬OK。シュノーケルスポット級の透明度。⚠️夏の海水浴場開設期間（7月中旬〜8月中旬 9〜16時）は指定海水浴場エリアのみ犬NG——島の南〜西側の磯浜を利用" },
    parking: [
      { name: "沖ノ島公園駐車場", fee: "無料", note: "約400台。夏は早朝に満車必至。水道なしのため犬の足洗い用の水持参" },
    ],
    restaurants: [
      { name: "ドッグ&ベジレストラン トゥルシー（館山市内）", policy: "テラスのみ", leadOK: false, note: "プチドッグラン併設・テラスはノーリード可の席あり" },
      { name: "カフェえどもんず", policy: "テラスのみ", leadOK: true, note: "館山の犬連れ定番カフェ" },
    ],
    surface: { shade: "多い", ground: "砂浜＋磯（岩場）。島内は海岸林で木陰豊富" },
    notes: "歩いて渡れる無人島。アクアライン経由で意外と近い。磯遊びと泳ぎの両方が楽しめる",
  },

  /* ---------- 湖 ---------- */
  {
    id: "yamanakako-hirano",
    name: "山中湖・平野の浜",
    category: "lake",
    area: "山梨県山中湖村",
    lat: 35.4149, lng: 138.8909, elevation_m: 982,
    driveMin: 100,
    water: { allowed: true, depth: "泳げる深さあり", note: "山中湖には犬の入水禁止規定がなく、通年犬の水遊び・遊泳実績多数。遠浅で徐々に深くなる。犬用ライフジャケット着用推奨（水温低め）" },
    parking: [
      { name: "平野の浜 湖畔無料駐車スペース", fee: "無料", note: "約10台。満車時は山中湖交流プラザきらら駐車場（300円）が徒歩圏" },
    ],
    restaurants: [
      { name: "SUGEEZ lil' frites（平野）", policy: "店内OK", leadOK: true, note: "全席犬同伴OKのバーガー・カフェ" },
      { name: "PICA山中湖 Hammock Cafe", policy: "店内OK", leadOK: true, note: "全席犬同伴OK（屋外ハンモック席）" },
    ],
    surface: { shade: "普通", ground: "砂浜（湖岸）＋一部草地。周辺に木陰あり" },
    notes: "逆さ富士の絶景スポット。波がなく穏やかで泳ぎ好きの犬に最適。標高982mで夏も涼しく熱中症リスクが低い。犬連れSUP/カヤック体験も豊富",
  },
  {
    id: "shibireko",
    name: "四尾連湖（水明荘湖畔）",
    category: "lake",
    area: "山梨県市川三郷町",
    lat: 35.5568, lng: 138.4553, elevation_m: 850,
    driveMin: 140,
    water: { allowed: true, depth: "泳げる深さあり", note: "ペット同伴可の湖で犬の遊泳禁止規定なし。岸近くから深くなり犬がしっかり泳げる。透明度高い。波・モーターボートなしで安全" },
    parking: [
      { name: "水明荘 第1・第2駐車場", fee: "500円/日", note: "湖畔まで徒歩すぐ。デイ利用可（湖畔利用料あり・要確認）" },
    ],
    restaurants: [
      { name: "水明荘 売店・軽食カフェ", policy: "テラスのみ", leadOK: true, note: "湖畔テラスで軽食" },
    ],
    surface: { shade: "多い", ground: "土・砂利の湖畔（森に囲まれた周囲1.2kmの山上湖）" },
    notes: "「ゆるキャン△」聖地の静かな山上湖。木陰が多く真夏でも過ごしやすい。混雑度低め。道中最後は狭い山道あり",
  },

  /* ---------- ドッグプール ---------- */
  {
    id: "wonderful-nature",
    name: "わんダフルネイチャーヴィレッジ",
    category: "pool",
    area: "東京都あきる野市",
    lat: 35.7270, lng: 139.2510, elevation_m: 190,
    driveMin: 70,
    water: { allowed: true, depth: "泳げる（ドッグビーチ最深60cm・280㎡）", note: "全犬種OKの屋外プール「ドッグビーチ」（噴水あり）。例年4〜10月頃、真夏は昼の部/夕涼みの部の2部制。犬1頭1,000〜2,500円/日＋入園料。WEB日時指定チケット制" },
    parking: [
      { name: "施設駐車場（サマーランド共用）", fee: "700円/日", note: "大規模駐車場で台数十分" },
    ],
    restaurants: [
      { name: "カフェ&レストラン アゼキリ（園内）", policy: "店内OK", leadOK: true, note: "全70席全席犬同伴OK。石窯ピザ・地元野菜メニュー" },
    ],
    surface: { shade: "普通", ground: "天然芝・ウッドチップ。プールサイドは日差し強め、夕涼み部も検討" },
    notes: "定休日は木曜中心（要公式カレンダー確認）。要ワクチン接種証明",
  },
  {
    id: "yadoriki",
    name: "寄（やどりき）七つ星ドッグラン＆カフェ",
    category: "pool",
    area: "神奈川県松田町",
    lat: 35.4076, lng: 139.1259, elevation_m: 340,
    driveMin: 75,
    water: { allowed: true, depth: "天然水プール（水遊び規模）", note: "山の天然水を引いた屋外ドッグプール。例年4〜10月中旬の季節限定。プール利用は入場料に込み（大人330円・犬440円）。6面以上のドッグラン" },
    parking: [
      { name: "施設駐車場", fee: "500円/1区画", note: "ドッグラン利用者用区画あり" },
    ],
    restaurants: [
      { name: "併設カフェ（七つ星カフェ）", policy: "店内OK", leadOK: true, note: "松田町産の旬野菜料理と犬用メニューあり" },
    ],
    surface: { shade: "多い", ground: "芝生・土（山あいの渓流沿いで木陰が多く夏も比較的涼しい）" },
    notes: "営業9:00〜17:00。定休日は火曜（祝日は営業）。要ワクチン接種証明。東名・大井松田IC経由",
  },
  {
    id: "fetch-kawagoe",
    name: "FETCH!（フェッチ）",
    category: "pool",
    area: "埼玉県川越市",
    lat: 35.9330, lng: 139.4300, elevation_m: 20,
    driveMin: 80,
    water: { allowed: true, depth: "泳げる（水深約1.2m）", note: "通年利用できる屋外ドッグプール。水深約1.2mで泳ぎ好きの犬向き（中型犬はライフジャケット推奨）。プール利用1,200円/頭" },
    parking: [
      { name: "店舗駐車場", fee: "無料", note: "郊外型店舗" },
    ],
    restaurants: [
      { name: "FETCH! 併設ドッグカフェ", policy: "店内OK", leadOK: true, note: "ドッグカフェ一体型施設のため店内同伴可" },
    ],
    surface: { shade: "普通", ground: "屋外ラン＋屋内ランあり（悪天候・猛暑時は屋内に退避可）" },
    notes: "営業10:00〜18:00、定休日は水・木曜。泳ぎ好きには関東でも数少ない「深さのある」通年プール。要ワクチン接種証明",
  },
  {
    id: "dogone-matsudo",
    name: "DOG ONE 松戸秋山",
    category: "pool",
    area: "千葉県松戸市",
    lat: 35.7520, lng: 139.9330, elevation_m: 25,
    driveMin: 60,
    water: { allowed: true, depth: "犬用プール（中型犬用タイムあり）", note: "夏季限定で屋外犬用プールを開放。小型犬と中型犬でタイム分けあり、12kgコーギーは中型犬枠。料金は要問合せ" },
    parking: [
      { name: "施設駐車場", fee: "無料", note: "約50台完備" },
    ],
    restaurants: [
      { name: "DOG ONE レストラン（併設）", policy: "店内OK", leadOK: true, note: "愛犬用メニューあり" },
    ],
    surface: { shade: "普通", ground: "天然芝" },
    notes: "ドッグラン営業9:00〜19:00（夏季〜20:00）、定休日は不定期（SNSで告知）。川崎から最も近い候補の一つ",
  },
  {
    id: "doggys-island",
    name: "小谷流の里 ドギーズアイランド",
    category: "pool",
    area: "千葉県八街市",
    lat: 35.6910, lng: 140.2540, elevation_m: 50,
    driveMin: 90,
    water: { allowed: true, depth: "泳げる（中〜大型犬用プール最大水深80cm）", note: "日本最大級ドッグリゾート。中〜大型犬専用ラン内プール（最大80cm）、じゃぶじゃぶ池など複数の水遊び場。日帰り入場：大人1,000〜1,200円、中型犬1,000〜1,300円" },
    parking: [
      { name: "施設駐車場", fee: "800円/日", note: "大規模駐車場あり。宿泊者は無料" },
    ],
    restaurants: [
      { name: "施設内レストラン（ワンズガーデン等）", policy: "店内OK", leadOK: true, note: "リゾート内レストランは愛犬同伴可。犬用メニューあり" },
    ],
    surface: { shade: "普通", ground: "天然芝（広大な芝生ラン、散策路あり）" },
    notes: "日帰り9:00〜21:00。定休日なし（メンテ休業あり）。要ワクチン接種証明。アクアライン経由",
  },
  {
    id: "woof-yamanakako",
    name: "ドッグリゾートWoof（山中湖）",
    category: "pool",
    area: "山梨県山中湖村",
    lat: 35.4243, lng: 138.8952, elevation_m: 990,
    driveMin: 100,
    water: { allowed: true, depth: "泳げる（屋内25mプール・水深1m超）", note: "約3万㎡の犬用複合リゾート。屋内温水25mプールは通年営業で泳ぎ好きの中型犬に最適。屋外温水プール（春〜夏）も。日帰りプール1,844円/頭〜" },
    parking: [
      { name: "施設駐車場", fee: "無料", note: "敷地内駐車場あり" },
    ],
    restaurants: [
      { name: "Woof カフェ&レストラン（館内）", policy: "店内OK", leadOK: true, note: "犬同伴可のドッグカフェ・レストラン併設。犬用メニューあり" },
    ],
    surface: { shade: "多い", ground: "芝生・土のドッグラン＋屋内ラン（標高約1,000mで夏も涼しい）" },
    notes: "施設9:00〜18:00頃。雨天・猛暑でも屋内プールで泳げるのが強み。東名〜東富士五湖道路山中湖IC経由",
  },
  {
    id: "aiken-izukogen",
    name: "愛犬の駅 伊豆高原",
    category: "pool",
    area: "静岡県伊東市",
    lat: 34.8770, lng: 139.1030, elevation_m: 140,
    driveMin: 150,
    water: { allowed: true, depth: "わんこプール（夏季限定）", note: "屋外ドッグランに夏季限定（例年7/1〜）で「わんこプール」が登場。タオル・ドライヤー完備。屋内ドッグランもあり" },
    parking: [
      { name: "施設駐車場", fee: "無料", note: "10:00〜18:00利用可" },
    ],
    restaurants: [
      { name: "併設カフェ（愛犬の駅内）", policy: "店内OK", leadOK: true, note: "店内・テラスとも犬同伴OK。犬用メニューあり" },
    ],
    surface: { shade: "普通", ground: "屋外ラン＋屋内ラン（真夏の日中は屋内に退避可）" },
    notes: "営業10:00〜18:00、年中無休。伊豆ぐらんぱる公園至近で観光と組み合わせやすい。片道約2.5時間と日帰り圏の上限",
  },
];
